export const books = [ 
    { id: 1, bookName: "1984", author: "George Orwell", country: "UK", yearOfPublish: 1949 },
  { id: 3, bookName: "The Adventures of Tom Sawyer", author: "Mark Twain", country: "USA", yearOfPublish: 1876 },
  { id: 4, bookName: "War and Peace", author: "Leo Tolstoy", country: "Russia", yearOfPublish: 1869 },
  { id: 5, bookName: "Pride and Prejudice", author: "Jane Austen", country: "UK", yearOfPublish: 1813 },
  { id: 6, bookName: "The Great Gatsby", author: "F. Scott Fitzgerald", country: "USA", yearOfPublish: 1925 },
  { id: 7, bookName: "Moby-Dick", author: "Herman Melville", country: "USA", yearOfPublish: 1851 },
  { id: 8, bookName: "Crime and Punishment", author: "Fyodor Dostoevsky", country: "Russia", yearOfPublish: 1866 },
  { id: 9, bookName: "Don Quixote", author: "Miguel de Cervantes", country: "Spain", yearOfPublish: 1605 },
  { id: 10, bookName: "The Catcher in the Rye", author: "J.D. Salinger", country: "USA", yearOfPublish: 1951 },
  { id: 11, bookName: "The Hobbit", author: "J.R.R. Tolkien", country: "UK", yearOfPublish: 1937 },
  { id: 12, bookName: "Brave New World", author: "Aldous Huxley", country: "UK", yearOfPublish: 1932 },
  { id: 13, bookName: "Ulysses", author: "James Joyce", country: "Ireland", yearOfPublish: 1922 },
  { id: 14, bookName: "Fahrenheit 451", author: "Ray Bradbury", country: "USA", yearOfPublish: 1953 },
  { id: 15, bookName: "The Lord of the Rings", author: "J.R.R. Tolkien", country: "UK", yearOfPublish: 1954 },
  { id: 16, bookName: "To Kill a Mockingbird", author: "Harper Lee", country: "USA", yearOfPublish: 1960 },
  { id: 17, bookName: "Dracula", author: "Bram Stoker", country: "Ireland", yearOfPublish: 1897 },
  { id: 18, bookName: "The Odyssey", author: "Homer", country: "Greece", yearOfPublish: -800 },
  { id: 19, bookName: "The Iliad", author: "Homer", country: "Greece", yearOfPublish: -762 },
  { id: 20, bookName: "The Divine Comedy", author: "Dante Alighieri", country: "Italy", yearOfPublish: 1320 },
  { id: 21, bookName: "Wuthering Heights", author: "Emily Brontë", country: "UK", yearOfPublish: 1847 },
  { id: 22, bookName: "The Picture of Dorian Gray", author: "Oscar Wilde", country: "Ireland", yearOfPublish: 1890 },
  { id: 23, bookName: "Jane Eyre", author: "Charlotte Brontë", country: "UK", yearOfPublish: 1847 },
  { id: 24, bookName: "Frankenstein", author: "Mary Shelley", country: "UK", yearOfPublish: 1818 },
  { id: 25, bookName: "The Count of Monte Cristo", author: "Alexandre Dumas", country: "France", yearOfPublish: 1844 },
  { id: 26, bookName: "Les Misérables", author: "Victor Hugo", country: "France", yearOfPublish: 1862 },
  { id: 27, bookName: "The Brothers Karamazov", author: "Fyodor Dostoevsky", country: "Russia", yearOfPublish: 1880 },
  { id: 28, bookName: "Anna Karenina", author: "Leo Tolstoy", country: "Russia", yearOfPublish: 1878 },
  { id: 30, bookName: "The Metamorphosis", author: "Franz Kafka", country: "Austria", yearOfPublish: 1915 },
  { id: 31, bookName: "The Old Man and the Sea", author: "Ernest Hemingway", country: "USA", yearOfPublish: 1952 },
  { id: 32, bookName: "Madame Bovary", author: "Gustave Flaubert", country: "France", yearOfPublish: 1856 },
  { id: 33, bookName: "A Tale of Two Cities", author: "Charles Dickens", country: "UK", yearOfPublish: 1859 },
  { id: 34, bookName: "David Copperfield", author: "Charles Dickens", country: "UK", yearOfPublish: 1850 },
  { id: 35, bookName: "Great Expectations", author: "Charles Dickens", country: "UK", yearOfPublish: 1861 },
  { id: 36, bookName: "The Jungle Book", author: "Rudyard Kipling", country: "UK", yearOfPublish: 1894 },
  { id: 37, bookName: "Gulliver's Travels", author: "Jonathan Swift", country: "Ireland", yearOfPublish: 1726 },
  { id: 38, bookName: "The War of the Worlds", author: "H.G. Wells", country: "UK", yearOfPublish: 1898 },
  { id: 39, bookName: "20,000 Leagues Under the Sea", author: "Jules Verne", country: "France", yearOfPublish: 1870 },
  { id: 40, bookName: "Around the World in Eighty Days", author: "Jules Verne", country: "France", yearOfPublish: 1873 },
  { id: 41, bookName: "The Scarlet Letter", author: "Nathaniel Hawthorne", country: "USA", yearOfPublish: 1850 },
  { id: 42, bookName: "A Christmas Carol", author: "Charles Dickens", country: "UK", yearOfPublish: 1843 },
  { id: 43, bookName: "Robinson Crusoe", author: "Daniel Defoe", country: "UK", yearOfPublish: 1719 },
  { id: 44, bookName: "Mansfield Park", author: "Jane Austen", country: "UK", yearOfPublish: 1814 },
  { id: 45, bookName: "Emma", author: "Jane Austen", country: "UK", yearOfPublish: 1815 },
  { id: 46, bookName: "Sense and Sensibility", author: "Jane Austen", country: "UK", yearOfPublish: 1811 },
  { id: 47, bookName: "The Time Machine", author: "H.G. Wells", country: "UK", yearOfPublish: 1895 },
  { id: 48, bookName: "The Secret Garden", author: "Frances Hodgson Burnett", country: "UK", yearOfPublish: 1911 },
  { id: 49, bookName: "Dr. Jekyll and Mr. Hyde", author: "Robert Louis Stevenson", country: "UK", yearOfPublish: 1886 },
  { id: 50, bookName: "Treasure Island", author: "Robert Louis Stevenson", country: "UK", yearOfPublish: 1883 }
  ];